### ISSUE TITLE
Profiler not outputting any data

### ISSUE THREAD

**Issue by westingham** [Zeex/samp-plugin-profiler#14]
I recently updated from a much older version of this plugin to the most recent one and now it won't output any data when the server is closed. The usual gamemode-profile.html file is created, but it only contains the HTML for the column headers.

![profiler](https://cloud.githubusercontent.com/assets/3617783/5792145/18b82a42-9ecf-11e4-96df-f27dfeee2094.jpg)

The server log shows the plugin attaching to the gamemode, no errors there; It also shows no errors when the server closes, just that the profiler is writing data.

Any idea why this might be happening?

**Comment by Zeex** [comment]
What version of profiler are you using and what operating system? Also, are you loading it together with any other plugins? If yes, I'd like to know which ones.

**Comment by westingham** [comment]
profiler-2.12.1
Ubuntu 14.04.1 LTS
plugins crashdetect.so sscanf.so streamer.so filemanager.so Whirlpool_Ubun12_64-bit.so mysql_static.so irc.so nativechecker.so profiler.so

**Comment by Zeex** [comment]
Is it streamer 2.7.5? If not, try updating to 2.7.5.

**Comment by westingham** [comment]
Switching to streamer 2.7.5 did the trick, thank you!

**Comment by Zeex** [comment]
OK, closing this then.
