### ISSUE TITLE
Native to force saving of profiling data

### ISSUE THREAD

**Issue by JernejL** [Zeex/samp-plugin-profiler#15]
Can a native be please added so we can manually force saving of data? 
 
I am having difficulties making server store data, because some plugins are causing a crash during each /gmx and no data is saved.

**Comment by Zeex** [comment]
There's Profiler_Dump() native:
https://github.com/Zeex/samp-plugin-profiler/blob/master/include/profiler.inc#L42

Is this what you're looking for?

**Comment by JernejL** [comment]
Shiiiiit.. i feel dumb :stars:
