### ISSUE TITLE
compiling instructions

### ISSUE THREAD

**Issue by JernejL** [Zeex/samp-plugin-profiler#17]
How exactly do i compile this.. windows and linux? i'll try some things in source to figure out why the profiler fails to work on my script / server.

**Comment by Zeex** [comment]
See compile instructions for crashdetect, they are very similar:

https://github.com/Zeex/samp-plugin-crashdetect#building-on-linux
https://github.com/Zeex/samp-plugin-crashdetect#building-on-windows
