### ISSUE TITLE
Profiler_Dump() crashed

### ISSUE THREAD

**Issue by X337** [Zeex/samp-plugin-profiler#22]
Profiler v2.14
Profiler_Dump() crashed in my PC (Windows 7), i've even tried to run the plugin with grand larceny gamemode and it's crashed too whenever i try to call this function.
But, in the previous version (v2.13), Profiler_Dump() worked fine.

Here is my server_log:

> [16:20:07] [profiler] Started profiling gamemodes/grandlarc
[16:20:07] Number of vehicle models: 173
[16:20:18] [profiler] Dumping profiling statistics for gamemodes/grandlarc
and samp_server.exe crashed

**Comment by Zeex** [comment]
Where do you call `Profiler_Dump()` from? What flags did you use to compile Grand Larceny?

**Comment by X337** [comment]
I'm using -d3 to compile, and i call `Profiler_Dump()` in a timer, 10 seconds after the gamemode init.

**Comment by Abyss-z94** [comment]
same problem, Profiler_Dump(); make my server crash too.
