### ISSUE TITLE
Conflicting include guards with profiler.inc from amx_assembly

### ISSUE THREAD

**Issue by kristoisberg** [Zeex/samp-plugin-profiler#27]
No further explanation needed.

**Comment by mrAlexZT** [comment]
Any news?

**Comment by Zeex** [comment]
Why are you including 2 profilers at once?

**Comment by kristoisberg** [comment]
At the time I created this issue YSI was including the basic one for some reason while I was using this one.

**Comment by Zeex** [comment]
OK, thanks for letting me know, I've changed the name to `PROFILER_PROFILER_INC`.
