### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by jerryle** [Zeex/samp-plugin-profiler#30]
hi, i tried to use this plugin but it keep crashing the server after starting a few seconds..
and get this cd log: https://hastebin.com/zokesuguzi.pas

plugins: profiler v2.15, crashdetect v4.18, pawnraknet 1.0.2, streamer 2.9.3, sscanf 2.8.2, pawn-memory
server: centos linux v7.4.1708

**Comment by Zeex** [comment]
Try removing profiler and swapping profiler and pawnraknet

**Comment by jerryle** [comment]
After swapping profiler and pawnraknet like you said, it is now working like a charm. Thanks a lot!
