### ISSUE TITLE
assertion failed on (call_graph_.root() != call_graph_.sentinel())

### ISSUE THREAD

**Issue by AGraber** [Zeex/samp-plugin-profiler#32]
Both are the same address:
https://github.com/Zeex/profiler/blob/148f731349b95fa17dc700e1eaa6b7b0dde3b5f3/src/amxprof/profiler.cpp#L170-L173

**Comment by Zeex** [comment]
Thanks, I've fixed a couple of bugs with the call graph feature, I think it should work now.
