### ISSUE TITLE
LeaveFunction

### ISSUE THREAD

**Issue by Romz24** [Zeex/samp-plugin-profiler#34]
No arguments are passed to the function, is this an error?

https://github.com/Zeex/samp-plugin-profiler/blob/master/src/amxprof/profiler.cpp#L70

**Comment by Zeex** [comment]
No, its parameter has a default value

https://github.com/Zeex/samp-plugin-profiler/blob/3778b2ed4b4e38034ab39c0d7771e8c9ace26ae3/src/amxprof/profiler.h#L80
