### ISSUE TITLE
tablesorter.com is down

### ISSUE THREAD

**Issue by Y-Less** [Zeex/samp-plugin-profiler#36]
http://tablesorter.com/__jquery.tablesorter.min.js

Doesn't work any more, so the generated results aren't sortable.  Speaking of, I was quite surprised when I first found out that the sorting actually required an external domain because I had no internet at the time.

**Comment by ziggi** [comment]
Already fixed in f67264cee755fb421421cb69b3d4f409a1d27a3e

**Comment by Zeex** [comment]
I'm working on a fix, I think I'll just remove external JS and rewrite the sorting feature using vanilla JS and then release a new version.
